### ISSUE TITLE
Preferred channel of communication

### ISSUE THREAD

**Issue by alxthmpson** [bhaskar10h/Terminal-Chat-App#2]
Hi @bhaskar10h,

What would be your preferred channel of communication? I wanted to talk to you regarding a project that I've been thinking to start.

Thanks!

**Comment by alxthmpson** [comment]
@bhaskar10h, Just a reminder :)

**Comment by bhaskar10h** [comment]
you connect me through Instagram : bhaskar_matrix
or through whatsapp : +91-9611324521

**Comment by alxthmpson** [comment]
Thank you!

**Comment by alxthmpson** [comment]
Hi @bhaskar10h, I saw your Twitter profile and your posts/replies are very inappropriate.

Sorry, I will not be contacting you.

All the best!
